### ISSUE TITLE
Mangler strømkontakt til styreenhet

### ISSUE THREAD

**Issue by Jaknil** [robotikklinja/veiecelle#2]
Kontrollenheten kan ikke kobles inn uten en speciell kontakt. 
![image](https://user-images.githubusercontent.com/3476653/70248331-032e3e80-177b-11ea-87bc-b2947af9e08e.png)

Petter har tatt mål på den. Notater:
![image](https://user-images.githubusercontent.com/3476653/70248422-2a850b80-177b-11ea-8b30-8cef93fb4fd3.png)

Jeg tolker notaterne som:
Pin spacing center to center = 4,5 mm
Plug width = 13,4 mm
Plug heigth = 5 mm
Plug depth = 11,56 mm

*0,9 ca cm målet vet jeg ikke hva det henviser til?* Eller er det som er pinne-avstånden?*
*Bredden på pinnerne er ikke målt opp?*

Jeg har to rekommandasjoner for å løse problemet.
1. Dere kanskje kan finne reservedel fra leveraktør av kontrollenheten. Gå på hjemmesiden til produktet og se om den kan bestilles. Hvis dere finner en link eller et artikkelnummer så bestiller vi den.
2. Finn [krympeterminaler ](https://www.elfadistrelec.no/no/kontakter/krympeterminaler-og-endehylser/krympeterminaler/c/cat-DNAV_PL_090412?q=*&filter_Buyable=1&filter_Category3=Krympeterminaler&filter_Kj%C3%B8nn=Hunn&filter_Kj%C3%B8nn=Hylse&filter_Kj%C3%B8nn=Sokkel) som dere trur skulle passe så bestiller vi dem. De koster neste ikke noe så vi kan bestille flere størrelser, dere må velge ut de dere ønsker.

Lykke til!

**Comment by petterbaro** [comment]
noen bestillinger som kanskje fungerer


https://www.elfadistrelec.no/no/krympeterminal-sokkel-tinn-over-nikkel-18awg-molex-206460-0031/p/30157380?q=*&pos=1&origPos=2&origPageSize=10&track=true

https://www.elfadistrelec.no/no/krympeterminal-hunn-tinn-18awg-20awg-molex-45750-1112/p/14402660?q=*&pos=22&origPos=18&origPageSize=10&track=true

https://www.elfadistrelec.no/no/krympestift-hunn-hunn-tinn-22-28awg-molex-39-00-0047/p/14402245?q=*&pos=6&origPos=40&origPageSize=10&track=true

**Comment by Jaknil** [comment]
Då har jeg lagt inn en behovsmedling på dem så vi har det etter jul. Tog 10 stk av hver. 
Ting vi trenger fremover kan legges inn på denne liste: https://github.com/robotikklinja/utstyr/blob/master/Bestillinger.md
